package com.egs.app.types;

public enum RestError {
	
	EMPTY_USER,
	EMPTY_USER_ID,
	EMPTY_SESSION_ID,
	EMPTY_ENTITY_ID,
	EMPTY_HIT_CATEGORY,
	EMPTY_CLUB_TYPE,
	CREATE_DUPLICATE_KEY,
	ENTITY_NOT_FOUND,
	ENTITY_NOT_FOUND_BY_ID,
	INVALID_VALUE,
	MISSED_VALUE,
	UNKNOWN

}
